services:
  capsulog:
    image: ghcr.io/gabrieledettorre/capsulog:latest
    container_name: capsulog
    ports:
      - "4316:3000"
    volumes:
      - /mnt/pve/ssd-sata/docker/capsulog/data:/app/data
    restart: unless-stopped