version: '3.8'

services:
  capsulog:
    build: .
    container_name: capsulog
    ports:
      - "4316:3000"
    volumes:
      - /mnt/pve/ssd-sata/docker/capsulog/data:/app/data
    restart: unless-stopped